// Generated by `wit-bindgen` 0.27.0. DO NOT EDIT!
#include "renderer.h"
#include <stdlib.h>

// Imported Functions from `flutter:widgets/alignment`

__attribute__((__import_module__("flutter:widgets/alignment"), __import_name__("[constructor]alignment")))
extern int32_t __wasm_import_flutter_widgets_alignment_constructor_alignment(double, double);

__attribute__((__import_module__("flutter:widgets/alignment"), __import_name__("[constructor]alignment-directional")))
extern int32_t __wasm_import_flutter_widgets_alignment_constructor_alignment_directional(double, double);

// Imported Functions from `flutter:widgets/widget`

__attribute__((__import_module__("flutter:widgets/widget"), __import_name__("[constructor]col")))
extern int32_t __wasm_import_flutter_widgets_widget_constructor_col(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uint8_t *, size_t);

__attribute__((__import_module__("flutter:widgets/widget"), __import_name__("[constructor]row")))
extern int32_t __wasm_import_flutter_widgets_widget_constructor_row(uint8_t *, size_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

// Exported Functions from `renderer`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("flutter:widgets/alignment"), __import_name__("[resource-drop]alignment")))
extern void __wasm_import_flutter_widgets_alignment_alignment_drop(int32_t handle);

void flutter_widgets_alignment_alignment_drop_own(flutter_widgets_alignment_own_alignment_t handle) {
  __wasm_import_flutter_widgets_alignment_alignment_drop(handle.__handle);
}

flutter_widgets_alignment_borrow_alignment_t flutter_widgets_alignment_borrow_alignment(flutter_widgets_alignment_own_alignment_t arg) {
  return (flutter_widgets_alignment_borrow_alignment_t) { arg.__handle };
}

__attribute__((__import_module__("flutter:widgets/alignment"), __import_name__("[resource-drop]alignment-directional")))
extern void __wasm_import_flutter_widgets_alignment_alignment_directional_drop(int32_t handle);

void flutter_widgets_alignment_alignment_directional_drop_own(flutter_widgets_alignment_own_alignment_directional_t handle) {
  __wasm_import_flutter_widgets_alignment_alignment_directional_drop(handle.__handle);
}

flutter_widgets_alignment_borrow_alignment_directional_t flutter_widgets_alignment_borrow_alignment_directional(flutter_widgets_alignment_own_alignment_directional_t arg) {
  return (flutter_widgets_alignment_borrow_alignment_directional_t) { arg.__handle };
}

void flutter_widgets_alignment_alignment_geometry_free(flutter_widgets_alignment_alignment_geometry_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
  }
}

void flutter_widgets_enums_main_axis_alignment_free(flutter_widgets_enums_main_axis_alignment_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_widgets_enums_text_direction_free(flutter_widgets_enums_text_direction_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_widgets_enums_vertical_direction_free(flutter_widgets_enums_vertical_direction_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_widgets_enums_main_axis_size_free(flutter_widgets_enums_main_axis_size_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_widgets_enums_text_baseline_free(flutter_widgets_enums_text_baseline_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_widgets_enums_cross_axis_alignment_free(flutter_widgets_enums_cross_axis_alignment_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_widgets_widget_alignment_geometry_free(flutter_widgets_widget_alignment_geometry_t *ptr) {
  flutter_widgets_alignment_alignment_geometry_free(ptr);
}

void flutter_widgets_widget_cross_axis_alignment_free(flutter_widgets_widget_cross_axis_alignment_t *ptr) {
  flutter_widgets_enums_cross_axis_alignment_free(ptr);
}

void flutter_widgets_widget_main_axis_alignment_free(flutter_widgets_widget_main_axis_alignment_t *ptr) {
  flutter_widgets_enums_main_axis_alignment_free(ptr);
}

void flutter_widgets_widget_main_axis_size_free(flutter_widgets_widget_main_axis_size_t *ptr) {
  flutter_widgets_enums_main_axis_size_free(ptr);
}

void flutter_widgets_widget_text_direction_free(flutter_widgets_widget_text_direction_t *ptr) {
  flutter_widgets_enums_text_direction_free(ptr);
}

void flutter_widgets_widget_text_baseline_free(flutter_widgets_widget_text_baseline_t *ptr) {
  flutter_widgets_enums_text_baseline_free(ptr);
}

void flutter_widgets_widget_vertical_direction_free(flutter_widgets_widget_vertical_direction_t *ptr) {
  flutter_widgets_enums_vertical_direction_free(ptr);
}

__attribute__((__import_module__("flutter:widgets/widget"), __import_name__("[resource-drop]col")))
extern void __wasm_import_flutter_widgets_widget_col_drop(int32_t handle);

void flutter_widgets_widget_col_drop_own(flutter_widgets_widget_own_col_t handle) {
  __wasm_import_flutter_widgets_widget_col_drop(handle.__handle);
}

flutter_widgets_widget_borrow_col_t flutter_widgets_widget_borrow_col(flutter_widgets_widget_own_col_t arg) {
  return (flutter_widgets_widget_borrow_col_t) { arg.__handle };
}

__attribute__((__import_module__("flutter:widgets/widget"), __import_name__("[resource-drop]row")))
extern void __wasm_import_flutter_widgets_widget_row_drop(int32_t handle);

void flutter_widgets_widget_row_drop_own(flutter_widgets_widget_own_row_t handle) {
  __wasm_import_flutter_widgets_widget_row_drop(handle.__handle);
}

flutter_widgets_widget_borrow_row_t flutter_widgets_widget_borrow_row(flutter_widgets_widget_own_row_t arg) {
  return (flutter_widgets_widget_borrow_row_t) { arg.__handle };
}

void flutter_widgets_widget_widget_free(flutter_widgets_widget_widget_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
  }
}

void flutter_widgets_widget_option_cross_axis_alignment_free(flutter_widgets_widget_option_cross_axis_alignment_t *ptr) {
  if (ptr->is_some) {
    flutter_widgets_widget_cross_axis_alignment_free(&ptr->val);
  }
}

void flutter_widgets_widget_option_main_axis_alignment_free(flutter_widgets_widget_option_main_axis_alignment_t *ptr) {
  if (ptr->is_some) {
    flutter_widgets_widget_main_axis_alignment_free(&ptr->val);
  }
}

void flutter_widgets_widget_option_main_axis_size_free(flutter_widgets_widget_option_main_axis_size_t *ptr) {
  if (ptr->is_some) {
    flutter_widgets_widget_main_axis_size_free(&ptr->val);
  }
}

void flutter_widgets_widget_option_text_direction_free(flutter_widgets_widget_option_text_direction_t *ptr) {
  if (ptr->is_some) {
    flutter_widgets_widget_text_direction_free(&ptr->val);
  }
}

void flutter_widgets_widget_option_text_baseline_free(flutter_widgets_widget_option_text_baseline_t *ptr) {
  if (ptr->is_some) {
    flutter_widgets_widget_text_baseline_free(&ptr->val);
  }
}

void flutter_widgets_widget_option_vertical_direction_free(flutter_widgets_widget_option_vertical_direction_t *ptr) {
  if (ptr->is_some) {
    flutter_widgets_widget_vertical_direction_free(&ptr->val);
  }
}

void flutter_widgets_widget_list_widget_free(flutter_widgets_widget_list_widget_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    flutter_widgets_widget_widget_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      flutter_widgets_widget_widget_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void renderer_widget_free(renderer_widget_t *ptr) {
  flutter_widgets_widget_widget_free(ptr);
}

// Component Adapters

flutter_widgets_alignment_own_alignment_t flutter_widgets_alignment_constructor_alignment(double start, double y) {
  int32_t ret = __wasm_import_flutter_widgets_alignment_constructor_alignment(start, y);
  return (flutter_widgets_alignment_own_alignment_t) { ret };
}

flutter_widgets_alignment_own_alignment_directional_t flutter_widgets_alignment_constructor_alignment_directional(double start, double y) {
  int32_t ret = __wasm_import_flutter_widgets_alignment_constructor_alignment_directional(start, y);
  return (flutter_widgets_alignment_own_alignment_directional_t) { ret };
}

flutter_widgets_widget_own_col_t flutter_widgets_widget_constructor_col(flutter_widgets_widget_cross_axis_alignment_t *maybe_cross_axis_alignment, flutter_widgets_widget_main_axis_alignment_t *maybe_main_axis_alignment, flutter_widgets_widget_main_axis_size_t *maybe_main_axis_size, flutter_widgets_widget_text_direction_t *maybe_text_direction, flutter_widgets_widget_text_baseline_t *maybe_text_baseline, flutter_widgets_widget_vertical_direction_t *maybe_vertical_direction, flutter_widgets_widget_list_widget_t *children) {
  flutter_widgets_widget_option_cross_axis_alignment_t cross_axis_alignment;
  cross_axis_alignment.is_some = maybe_cross_axis_alignment != NULL;if (maybe_cross_axis_alignment) {
    cross_axis_alignment.val = *maybe_cross_axis_alignment;
  }
  flutter_widgets_widget_option_main_axis_alignment_t main_axis_alignment;
  main_axis_alignment.is_some = maybe_main_axis_alignment != NULL;if (maybe_main_axis_alignment) {
    main_axis_alignment.val = *maybe_main_axis_alignment;
  }
  flutter_widgets_widget_option_main_axis_size_t main_axis_size;
  main_axis_size.is_some = maybe_main_axis_size != NULL;if (maybe_main_axis_size) {
    main_axis_size.val = *maybe_main_axis_size;
  }
  flutter_widgets_widget_option_text_direction_t text_direction;
  text_direction.is_some = maybe_text_direction != NULL;if (maybe_text_direction) {
    text_direction.val = *maybe_text_direction;
  }
  flutter_widgets_widget_option_text_baseline_t text_baseline;
  text_baseline.is_some = maybe_text_baseline != NULL;if (maybe_text_baseline) {
    text_baseline.val = *maybe_text_baseline;
  }
  flutter_widgets_widget_option_vertical_direction_t vertical_direction;
  vertical_direction.is_some = maybe_vertical_direction != NULL;if (maybe_vertical_direction) {
    vertical_direction.val = *maybe_vertical_direction;
  }
  int32_t option;
  int32_t option6;
  if ((cross_axis_alignment).is_some) {
    const flutter_widgets_widget_cross_axis_alignment_t *payload0 = &(cross_axis_alignment).val;
    int32_t variant;
    switch ((int32_t) (*payload0).tag) {
      case 0: {
        variant = 0;
        break;
      }
      case 1: {
        variant = 1;
        break;
      }
      case 2: {
        variant = 2;
        break;
      }
      case 3: {
        variant = 3;
        break;
      }
      case 4: {
        variant = 4;
        break;
      }
    }
    option = 1;
    option6 = variant;
  } else {
    option = 0;
    option6 = 0;
  }
  int32_t option16;
  int32_t option17;
  if ((main_axis_alignment).is_some) {
    const flutter_widgets_widget_main_axis_alignment_t *payload8 = &(main_axis_alignment).val;
    int32_t variant15;
    switch ((int32_t) (*payload8).tag) {
      case 0: {
        variant15 = 0;
        break;
      }
      case 1: {
        variant15 = 1;
        break;
      }
      case 2: {
        variant15 = 2;
        break;
      }
      case 3: {
        variant15 = 3;
        break;
      }
      case 4: {
        variant15 = 4;
        break;
      }
      case 5: {
        variant15 = 5;
        break;
      }
    }
    option16 = 1;
    option17 = variant15;
  } else {
    option16 = 0;
    option17 = 0;
  }
  int32_t option23;
  int32_t option24;
  if ((main_axis_size).is_some) {
    const flutter_widgets_widget_main_axis_size_t *payload19 = &(main_axis_size).val;
    int32_t variant22;
    switch ((int32_t) (*payload19).tag) {
      case 0: {
        variant22 = 0;
        break;
      }
      case 1: {
        variant22 = 1;
        break;
      }
    }
    option23 = 1;
    option24 = variant22;
  } else {
    option23 = 0;
    option24 = 0;
  }
  int32_t option30;
  int32_t option31;
  if ((text_direction).is_some) {
    const flutter_widgets_widget_text_direction_t *payload26 = &(text_direction).val;
    int32_t variant29;
    switch ((int32_t) (*payload26).tag) {
      case 0: {
        variant29 = 0;
        break;
      }
      case 1: {
        variant29 = 1;
        break;
      }
    }
    option30 = 1;
    option31 = variant29;
  } else {
    option30 = 0;
    option31 = 0;
  }
  int32_t option37;
  int32_t option38;
  if ((text_baseline).is_some) {
    const flutter_widgets_widget_text_baseline_t *payload33 = &(text_baseline).val;
    int32_t variant36;
    switch ((int32_t) (*payload33).tag) {
      case 0: {
        variant36 = 0;
        break;
      }
      case 1: {
        variant36 = 1;
        break;
      }
    }
    option37 = 1;
    option38 = variant36;
  } else {
    option37 = 0;
    option38 = 0;
  }
  int32_t option44;
  int32_t option45;
  if ((vertical_direction).is_some) {
    const flutter_widgets_widget_vertical_direction_t *payload40 = &(vertical_direction).val;
    int32_t variant43;
    switch ((int32_t) (*payload40).tag) {
      case 0: {
        variant43 = 0;
        break;
      }
      case 1: {
        variant43 = 1;
        break;
      }
    }
    option44 = 1;
    option45 = variant43;
  } else {
    option44 = 0;
    option45 = 0;
  }
  int32_t ret = __wasm_import_flutter_widgets_widget_constructor_col(option, option6, option16, option17, option23, option24, option30, option31, option37, option38, option44, option45, (uint8_t *) (*children).ptr, (*children).len);
  return (flutter_widgets_widget_own_col_t) { ret };
}

flutter_widgets_widget_own_row_t flutter_widgets_widget_constructor_row(flutter_widgets_widget_list_widget_t *children, flutter_widgets_widget_cross_axis_alignment_t *maybe_cross_axis_alignment, flutter_widgets_widget_main_axis_alignment_t *maybe_main_axis_alignment, flutter_widgets_widget_main_axis_size_t *maybe_main_axis_size, flutter_widgets_widget_text_direction_t *maybe_text_direction, flutter_widgets_widget_text_baseline_t *maybe_text_baseline, flutter_widgets_widget_vertical_direction_t *maybe_vertical_direction) {
  flutter_widgets_widget_option_cross_axis_alignment_t cross_axis_alignment;
  cross_axis_alignment.is_some = maybe_cross_axis_alignment != NULL;if (maybe_cross_axis_alignment) {
    cross_axis_alignment.val = *maybe_cross_axis_alignment;
  }
  flutter_widgets_widget_option_main_axis_alignment_t main_axis_alignment;
  main_axis_alignment.is_some = maybe_main_axis_alignment != NULL;if (maybe_main_axis_alignment) {
    main_axis_alignment.val = *maybe_main_axis_alignment;
  }
  flutter_widgets_widget_option_main_axis_size_t main_axis_size;
  main_axis_size.is_some = maybe_main_axis_size != NULL;if (maybe_main_axis_size) {
    main_axis_size.val = *maybe_main_axis_size;
  }
  flutter_widgets_widget_option_text_direction_t text_direction;
  text_direction.is_some = maybe_text_direction != NULL;if (maybe_text_direction) {
    text_direction.val = *maybe_text_direction;
  }
  flutter_widgets_widget_option_text_baseline_t text_baseline;
  text_baseline.is_some = maybe_text_baseline != NULL;if (maybe_text_baseline) {
    text_baseline.val = *maybe_text_baseline;
  }
  flutter_widgets_widget_option_vertical_direction_t vertical_direction;
  vertical_direction.is_some = maybe_vertical_direction != NULL;if (maybe_vertical_direction) {
    vertical_direction.val = *maybe_vertical_direction;
  }
  int32_t option;
  int32_t option8;
  if ((cross_axis_alignment).is_some) {
    const flutter_widgets_widget_cross_axis_alignment_t *payload2 = &(cross_axis_alignment).val;
    int32_t variant;
    switch ((int32_t) (*payload2).tag) {
      case 0: {
        variant = 0;
        break;
      }
      case 1: {
        variant = 1;
        break;
      }
      case 2: {
        variant = 2;
        break;
      }
      case 3: {
        variant = 3;
        break;
      }
      case 4: {
        variant = 4;
        break;
      }
    }
    option = 1;
    option8 = variant;
  } else {
    option = 0;
    option8 = 0;
  }
  int32_t option18;
  int32_t option19;
  if ((main_axis_alignment).is_some) {
    const flutter_widgets_widget_main_axis_alignment_t *payload10 = &(main_axis_alignment).val;
    int32_t variant17;
    switch ((int32_t) (*payload10).tag) {
      case 0: {
        variant17 = 0;
        break;
      }
      case 1: {
        variant17 = 1;
        break;
      }
      case 2: {
        variant17 = 2;
        break;
      }
      case 3: {
        variant17 = 3;
        break;
      }
      case 4: {
        variant17 = 4;
        break;
      }
      case 5: {
        variant17 = 5;
        break;
      }
    }
    option18 = 1;
    option19 = variant17;
  } else {
    option18 = 0;
    option19 = 0;
  }
  int32_t option25;
  int32_t option26;
  if ((main_axis_size).is_some) {
    const flutter_widgets_widget_main_axis_size_t *payload21 = &(main_axis_size).val;
    int32_t variant24;
    switch ((int32_t) (*payload21).tag) {
      case 0: {
        variant24 = 0;
        break;
      }
      case 1: {
        variant24 = 1;
        break;
      }
    }
    option25 = 1;
    option26 = variant24;
  } else {
    option25 = 0;
    option26 = 0;
  }
  int32_t option32;
  int32_t option33;
  if ((text_direction).is_some) {
    const flutter_widgets_widget_text_direction_t *payload28 = &(text_direction).val;
    int32_t variant31;
    switch ((int32_t) (*payload28).tag) {
      case 0: {
        variant31 = 0;
        break;
      }
      case 1: {
        variant31 = 1;
        break;
      }
    }
    option32 = 1;
    option33 = variant31;
  } else {
    option32 = 0;
    option33 = 0;
  }
  int32_t option39;
  int32_t option40;
  if ((text_baseline).is_some) {
    const flutter_widgets_widget_text_baseline_t *payload35 = &(text_baseline).val;
    int32_t variant38;
    switch ((int32_t) (*payload35).tag) {
      case 0: {
        variant38 = 0;
        break;
      }
      case 1: {
        variant38 = 1;
        break;
      }
    }
    option39 = 1;
    option40 = variant38;
  } else {
    option39 = 0;
    option40 = 0;
  }
  int32_t option46;
  int32_t option47;
  if ((vertical_direction).is_some) {
    const flutter_widgets_widget_vertical_direction_t *payload42 = &(vertical_direction).val;
    int32_t variant45;
    switch ((int32_t) (*payload42).tag) {
      case 0: {
        variant45 = 0;
        break;
      }
      case 1: {
        variant45 = 1;
        break;
      }
    }
    option46 = 1;
    option47 = variant45;
  } else {
    option46 = 0;
    option47 = 0;
  }
  int32_t ret = __wasm_import_flutter_widgets_widget_constructor_row((uint8_t *) (*children).ptr, (*children).len, option, option8, option18, option19, option25, option26, option32, option33, option39, option40, option46, option47);
  return (flutter_widgets_widget_own_row_t) { ret };
}

__attribute__((__export_name__("render")))
double __wasm_export_renderer_render(int32_t arg, int32_t arg0) {
  flutter_widgets_widget_widget_t variant;
  variant.tag = arg;
  switch ((int32_t) variant.tag) {
    case 0: {
      variant.val.col = (flutter_widgets_widget_own_col_t) { arg0 };
      break;
    }
    case 1: {
      variant.val.col = (flutter_widgets_widget_own_row_t) { arg0 };
      break;
    }
  }
  renderer_widget_t arg1 = variant;
  double ret = renderer_render(&arg1);
  return ret;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_renderer(void);
void __component_type_object_force_link_renderer_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_renderer();
}
