// Generated by `wit-bindgen` 0.27.0. DO NOT EDIT!
#include "plugin.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `flutter:renderer/alignment`

__attribute__((__import_module__("flutter:renderer/alignment"), __import_name__("[constructor]alignment")))
extern int32_t __wasm_import_flutter_renderer_alignment_constructor_alignment(double, double);

__attribute__((__import_module__("flutter:renderer/alignment"), __import_name__("[constructor]alignment-directional")))
extern int32_t __wasm_import_flutter_renderer_alignment_constructor_alignment_directional(double, double);

// Imported Functions from `flutter:renderer/widget`

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[constructor]row")))
extern int32_t __wasm_import_flutter_renderer_widget_constructor_row(uint8_t *, size_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[constructor]col")))
extern int32_t __wasm_import_flutter_renderer_widget_constructor_col(uint8_t *, size_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[constructor]text")))
extern int32_t __wasm_import_flutter_renderer_widget_constructor_text(uint8_t *, size_t);

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[constructor]text-rich")))
extern int32_t __wasm_import_flutter_renderer_widget_constructor_text_rich(void);

// Imported Functions from `flutter:renderer/renderer`

__attribute__((__import_module__("flutter:renderer/renderer"), __import_name__("[method]renderer.render")))
extern void __wasm_import_flutter_renderer_renderer_method_renderer_render(int32_t, int32_t, int32_t, uint8_t *);

// Exported Functions from `plugin`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("flutter:renderer/alignment"), __import_name__("[resource-drop]alignment")))
extern void __wasm_import_flutter_renderer_alignment_alignment_drop(int32_t handle);

void flutter_renderer_alignment_alignment_drop_own(flutter_renderer_alignment_own_alignment_t handle) {
  __wasm_import_flutter_renderer_alignment_alignment_drop(handle.__handle);
}

flutter_renderer_alignment_borrow_alignment_t flutter_renderer_alignment_borrow_alignment(flutter_renderer_alignment_own_alignment_t arg) {
  return (flutter_renderer_alignment_borrow_alignment_t) { arg.__handle };
}

__attribute__((__import_module__("flutter:renderer/alignment"), __import_name__("[resource-drop]alignment-directional")))
extern void __wasm_import_flutter_renderer_alignment_alignment_directional_drop(int32_t handle);

void flutter_renderer_alignment_alignment_directional_drop_own(flutter_renderer_alignment_own_alignment_directional_t handle) {
  __wasm_import_flutter_renderer_alignment_alignment_directional_drop(handle.__handle);
}

flutter_renderer_alignment_borrow_alignment_directional_t flutter_renderer_alignment_borrow_alignment_directional(flutter_renderer_alignment_own_alignment_directional_t arg) {
  return (flutter_renderer_alignment_borrow_alignment_directional_t) { arg.__handle };
}

void flutter_renderer_alignment_alignment_geometry_free(flutter_renderer_alignment_alignment_geometry_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
  }
}

void flutter_renderer_enums_main_axis_alignment_free(flutter_renderer_enums_main_axis_alignment_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_renderer_enums_text_direction_free(flutter_renderer_enums_text_direction_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_renderer_enums_vertical_direction_free(flutter_renderer_enums_vertical_direction_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_renderer_enums_main_axis_size_free(flutter_renderer_enums_main_axis_size_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_renderer_enums_text_baseline_free(flutter_renderer_enums_text_baseline_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_renderer_enums_cross_axis_alignment_free(flutter_renderer_enums_cross_axis_alignment_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

void flutter_renderer_widget_alignment_geometry_free(flutter_renderer_widget_alignment_geometry_t *ptr) {
  flutter_renderer_alignment_alignment_geometry_free(ptr);
}

void flutter_renderer_widget_cross_axis_alignment_free(flutter_renderer_widget_cross_axis_alignment_t *ptr) {
  flutter_renderer_enums_cross_axis_alignment_free(ptr);
}

void flutter_renderer_widget_main_axis_alignment_free(flutter_renderer_widget_main_axis_alignment_t *ptr) {
  flutter_renderer_enums_main_axis_alignment_free(ptr);
}

void flutter_renderer_widget_main_axis_size_free(flutter_renderer_widget_main_axis_size_t *ptr) {
  flutter_renderer_enums_main_axis_size_free(ptr);
}

void flutter_renderer_widget_text_direction_free(flutter_renderer_widget_text_direction_t *ptr) {
  flutter_renderer_enums_text_direction_free(ptr);
}

void flutter_renderer_widget_text_baseline_free(flutter_renderer_widget_text_baseline_t *ptr) {
  flutter_renderer_enums_text_baseline_free(ptr);
}

void flutter_renderer_widget_vertical_direction_free(flutter_renderer_widget_vertical_direction_t *ptr) {
  flutter_renderer_enums_vertical_direction_free(ptr);
}

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[resource-drop]row")))
extern void __wasm_import_flutter_renderer_widget_row_drop(int32_t handle);

void flutter_renderer_widget_row_drop_own(flutter_renderer_widget_own_row_t handle) {
  __wasm_import_flutter_renderer_widget_row_drop(handle.__handle);
}

flutter_renderer_widget_borrow_row_t flutter_renderer_widget_borrow_row(flutter_renderer_widget_own_row_t arg) {
  return (flutter_renderer_widget_borrow_row_t) { arg.__handle };
}

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[resource-drop]col")))
extern void __wasm_import_flutter_renderer_widget_col_drop(int32_t handle);

void flutter_renderer_widget_col_drop_own(flutter_renderer_widget_own_col_t handle) {
  __wasm_import_flutter_renderer_widget_col_drop(handle.__handle);
}

flutter_renderer_widget_borrow_col_t flutter_renderer_widget_borrow_col(flutter_renderer_widget_own_col_t arg) {
  return (flutter_renderer_widget_borrow_col_t) { arg.__handle };
}

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[resource-drop]text")))
extern void __wasm_import_flutter_renderer_widget_text_drop(int32_t handle);

void flutter_renderer_widget_text_drop_own(flutter_renderer_widget_own_text_t handle) {
  __wasm_import_flutter_renderer_widget_text_drop(handle.__handle);
}

flutter_renderer_widget_borrow_text_t flutter_renderer_widget_borrow_text(flutter_renderer_widget_own_text_t arg) {
  return (flutter_renderer_widget_borrow_text_t) { arg.__handle };
}

__attribute__((__import_module__("flutter:renderer/widget"), __import_name__("[resource-drop]text-rich")))
extern void __wasm_import_flutter_renderer_widget_text_rich_drop(int32_t handle);

void flutter_renderer_widget_text_rich_drop_own(flutter_renderer_widget_own_text_rich_t handle) {
  __wasm_import_flutter_renderer_widget_text_rich_drop(handle.__handle);
}

flutter_renderer_widget_borrow_text_rich_t flutter_renderer_widget_borrow_text_rich(flutter_renderer_widget_own_text_rich_t arg) {
  return (flutter_renderer_widget_borrow_text_rich_t) { arg.__handle };
}

void flutter_renderer_widget_widget_free(flutter_renderer_widget_widget_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    case 2: {
      break;
    }
    case 3: {
      break;
    }
  }
}

void flutter_renderer_widget_list_widget_free(flutter_renderer_widget_list_widget_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    flutter_renderer_widget_widget_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      flutter_renderer_widget_widget_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void flutter_renderer_widget_option_cross_axis_alignment_free(flutter_renderer_widget_option_cross_axis_alignment_t *ptr) {
  if (ptr->is_some) {
    flutter_renderer_widget_cross_axis_alignment_free(&ptr->val);
  }
}

void flutter_renderer_widget_option_main_axis_alignment_free(flutter_renderer_widget_option_main_axis_alignment_t *ptr) {
  if (ptr->is_some) {
    flutter_renderer_widget_main_axis_alignment_free(&ptr->val);
  }
}

void flutter_renderer_widget_option_main_axis_size_free(flutter_renderer_widget_option_main_axis_size_t *ptr) {
  if (ptr->is_some) {
    flutter_renderer_widget_main_axis_size_free(&ptr->val);
  }
}

void flutter_renderer_widget_option_text_direction_free(flutter_renderer_widget_option_text_direction_t *ptr) {
  if (ptr->is_some) {
    flutter_renderer_widget_text_direction_free(&ptr->val);
  }
}

void flutter_renderer_widget_option_text_baseline_free(flutter_renderer_widget_option_text_baseline_t *ptr) {
  if (ptr->is_some) {
    flutter_renderer_widget_text_baseline_free(&ptr->val);
  }
}

void flutter_renderer_widget_option_vertical_direction_free(flutter_renderer_widget_option_vertical_direction_t *ptr) {
  if (ptr->is_some) {
    flutter_renderer_widget_vertical_direction_free(&ptr->val);
  }
}

void flutter_renderer_renderer_widget_free(flutter_renderer_renderer_widget_t *ptr) {
  flutter_renderer_widget_widget_free(ptr);
}

void flutter_renderer_renderer_error_free(flutter_renderer_renderer_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
  }
}

__attribute__((__import_module__("flutter:renderer/renderer"), __import_name__("[resource-drop]renderer")))
extern void __wasm_import_flutter_renderer_renderer_renderer_drop(int32_t handle);

void flutter_renderer_renderer_renderer_drop_own(flutter_renderer_renderer_own_renderer_t handle) {
  __wasm_import_flutter_renderer_renderer_renderer_drop(handle.__handle);
}

flutter_renderer_renderer_borrow_renderer_t flutter_renderer_renderer_borrow_renderer(flutter_renderer_renderer_own_renderer_t arg) {
  return (flutter_renderer_renderer_borrow_renderer_t) { arg.__handle };
}

void flutter_renderer_renderer_option_error_free(flutter_renderer_renderer_option_error_t *ptr) {
  if (ptr->is_some) {
    flutter_renderer_renderer_error_free(&ptr->val);
  }
}

void plugin_error_free(plugin_error_t *ptr) {
  flutter_renderer_renderer_error_free(ptr);
}

void plugin_option_error_free(plugin_option_error_t *ptr) {
  if (ptr->is_some) {
    plugin_error_free(&ptr->val);
  }
}

void plugin_string_set(plugin_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void plugin_string_dup(plugin_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void plugin_string_free(plugin_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(1)))
static uint8_t RET_AREA[2];

flutter_renderer_alignment_own_alignment_t flutter_renderer_alignment_constructor_alignment(double start, double y) {
  int32_t ret = __wasm_import_flutter_renderer_alignment_constructor_alignment(start, y);
  return (flutter_renderer_alignment_own_alignment_t) { ret };
}

flutter_renderer_alignment_own_alignment_directional_t flutter_renderer_alignment_constructor_alignment_directional(double start, double y) {
  int32_t ret = __wasm_import_flutter_renderer_alignment_constructor_alignment_directional(start, y);
  return (flutter_renderer_alignment_own_alignment_directional_t) { ret };
}

flutter_renderer_widget_own_row_t flutter_renderer_widget_constructor_row(flutter_renderer_widget_list_widget_t *children, flutter_renderer_widget_cross_axis_alignment_t *maybe_cross_axis_alignment, flutter_renderer_widget_main_axis_alignment_t *maybe_main_axis_alignment, flutter_renderer_widget_main_axis_size_t *maybe_main_axis_size, flutter_renderer_widget_text_direction_t *maybe_text_direction, flutter_renderer_widget_text_baseline_t *maybe_text_baseline, flutter_renderer_widget_vertical_direction_t *maybe_vertical_direction) {
  flutter_renderer_widget_option_cross_axis_alignment_t cross_axis_alignment;
  cross_axis_alignment.is_some = maybe_cross_axis_alignment != NULL;if (maybe_cross_axis_alignment) {
    cross_axis_alignment.val = *maybe_cross_axis_alignment;
  }
  flutter_renderer_widget_option_main_axis_alignment_t main_axis_alignment;
  main_axis_alignment.is_some = maybe_main_axis_alignment != NULL;if (maybe_main_axis_alignment) {
    main_axis_alignment.val = *maybe_main_axis_alignment;
  }
  flutter_renderer_widget_option_main_axis_size_t main_axis_size;
  main_axis_size.is_some = maybe_main_axis_size != NULL;if (maybe_main_axis_size) {
    main_axis_size.val = *maybe_main_axis_size;
  }
  flutter_renderer_widget_option_text_direction_t text_direction;
  text_direction.is_some = maybe_text_direction != NULL;if (maybe_text_direction) {
    text_direction.val = *maybe_text_direction;
  }
  flutter_renderer_widget_option_text_baseline_t text_baseline;
  text_baseline.is_some = maybe_text_baseline != NULL;if (maybe_text_baseline) {
    text_baseline.val = *maybe_text_baseline;
  }
  flutter_renderer_widget_option_vertical_direction_t vertical_direction;
  vertical_direction.is_some = maybe_vertical_direction != NULL;if (maybe_vertical_direction) {
    vertical_direction.val = *maybe_vertical_direction;
  }
  int32_t option;
  int32_t option10;
  if ((cross_axis_alignment).is_some) {
    const flutter_renderer_widget_cross_axis_alignment_t *payload4 = &(cross_axis_alignment).val;
    int32_t variant;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        variant = 0;
        break;
      }
      case 1: {
        variant = 1;
        break;
      }
      case 2: {
        variant = 2;
        break;
      }
      case 3: {
        variant = 3;
        break;
      }
      case 4: {
        variant = 4;
        break;
      }
    }
    option = 1;
    option10 = variant;
  } else {
    option = 0;
    option10 = 0;
  }
  int32_t option20;
  int32_t option21;
  if ((main_axis_alignment).is_some) {
    const flutter_renderer_widget_main_axis_alignment_t *payload12 = &(main_axis_alignment).val;
    int32_t variant19;
    switch ((int32_t) (*payload12).tag) {
      case 0: {
        variant19 = 0;
        break;
      }
      case 1: {
        variant19 = 1;
        break;
      }
      case 2: {
        variant19 = 2;
        break;
      }
      case 3: {
        variant19 = 3;
        break;
      }
      case 4: {
        variant19 = 4;
        break;
      }
      case 5: {
        variant19 = 5;
        break;
      }
    }
    option20 = 1;
    option21 = variant19;
  } else {
    option20 = 0;
    option21 = 0;
  }
  int32_t option27;
  int32_t option28;
  if ((main_axis_size).is_some) {
    const flutter_renderer_widget_main_axis_size_t *payload23 = &(main_axis_size).val;
    int32_t variant26;
    switch ((int32_t) (*payload23).tag) {
      case 0: {
        variant26 = 0;
        break;
      }
      case 1: {
        variant26 = 1;
        break;
      }
    }
    option27 = 1;
    option28 = variant26;
  } else {
    option27 = 0;
    option28 = 0;
  }
  int32_t option34;
  int32_t option35;
  if ((text_direction).is_some) {
    const flutter_renderer_widget_text_direction_t *payload30 = &(text_direction).val;
    int32_t variant33;
    switch ((int32_t) (*payload30).tag) {
      case 0: {
        variant33 = 0;
        break;
      }
      case 1: {
        variant33 = 1;
        break;
      }
    }
    option34 = 1;
    option35 = variant33;
  } else {
    option34 = 0;
    option35 = 0;
  }
  int32_t option41;
  int32_t option42;
  if ((text_baseline).is_some) {
    const flutter_renderer_widget_text_baseline_t *payload37 = &(text_baseline).val;
    int32_t variant40;
    switch ((int32_t) (*payload37).tag) {
      case 0: {
        variant40 = 0;
        break;
      }
      case 1: {
        variant40 = 1;
        break;
      }
    }
    option41 = 1;
    option42 = variant40;
  } else {
    option41 = 0;
    option42 = 0;
  }
  int32_t option48;
  int32_t option49;
  if ((vertical_direction).is_some) {
    const flutter_renderer_widget_vertical_direction_t *payload44 = &(vertical_direction).val;
    int32_t variant47;
    switch ((int32_t) (*payload44).tag) {
      case 0: {
        variant47 = 0;
        break;
      }
      case 1: {
        variant47 = 1;
        break;
      }
    }
    option48 = 1;
    option49 = variant47;
  } else {
    option48 = 0;
    option49 = 0;
  }
  int32_t ret = __wasm_import_flutter_renderer_widget_constructor_row((uint8_t *) (*children).ptr, (*children).len, option, option10, option20, option21, option27, option28, option34, option35, option41, option42, option48, option49);
  return (flutter_renderer_widget_own_row_t) { ret };
}

flutter_renderer_widget_own_col_t flutter_renderer_widget_constructor_col(flutter_renderer_widget_list_widget_t *children, flutter_renderer_widget_cross_axis_alignment_t *maybe_cross_axis_alignment, flutter_renderer_widget_main_axis_alignment_t *maybe_main_axis_alignment, flutter_renderer_widget_main_axis_size_t *maybe_main_axis_size, flutter_renderer_widget_text_direction_t *maybe_text_direction, flutter_renderer_widget_text_baseline_t *maybe_text_baseline, flutter_renderer_widget_vertical_direction_t *maybe_vertical_direction) {
  flutter_renderer_widget_option_cross_axis_alignment_t cross_axis_alignment;
  cross_axis_alignment.is_some = maybe_cross_axis_alignment != NULL;if (maybe_cross_axis_alignment) {
    cross_axis_alignment.val = *maybe_cross_axis_alignment;
  }
  flutter_renderer_widget_option_main_axis_alignment_t main_axis_alignment;
  main_axis_alignment.is_some = maybe_main_axis_alignment != NULL;if (maybe_main_axis_alignment) {
    main_axis_alignment.val = *maybe_main_axis_alignment;
  }
  flutter_renderer_widget_option_main_axis_size_t main_axis_size;
  main_axis_size.is_some = maybe_main_axis_size != NULL;if (maybe_main_axis_size) {
    main_axis_size.val = *maybe_main_axis_size;
  }
  flutter_renderer_widget_option_text_direction_t text_direction;
  text_direction.is_some = maybe_text_direction != NULL;if (maybe_text_direction) {
    text_direction.val = *maybe_text_direction;
  }
  flutter_renderer_widget_option_text_baseline_t text_baseline;
  text_baseline.is_some = maybe_text_baseline != NULL;if (maybe_text_baseline) {
    text_baseline.val = *maybe_text_baseline;
  }
  flutter_renderer_widget_option_vertical_direction_t vertical_direction;
  vertical_direction.is_some = maybe_vertical_direction != NULL;if (maybe_vertical_direction) {
    vertical_direction.val = *maybe_vertical_direction;
  }
  int32_t option;
  int32_t option10;
  if ((cross_axis_alignment).is_some) {
    const flutter_renderer_widget_cross_axis_alignment_t *payload4 = &(cross_axis_alignment).val;
    int32_t variant;
    switch ((int32_t) (*payload4).tag) {
      case 0: {
        variant = 0;
        break;
      }
      case 1: {
        variant = 1;
        break;
      }
      case 2: {
        variant = 2;
        break;
      }
      case 3: {
        variant = 3;
        break;
      }
      case 4: {
        variant = 4;
        break;
      }
    }
    option = 1;
    option10 = variant;
  } else {
    option = 0;
    option10 = 0;
  }
  int32_t option20;
  int32_t option21;
  if ((main_axis_alignment).is_some) {
    const flutter_renderer_widget_main_axis_alignment_t *payload12 = &(main_axis_alignment).val;
    int32_t variant19;
    switch ((int32_t) (*payload12).tag) {
      case 0: {
        variant19 = 0;
        break;
      }
      case 1: {
        variant19 = 1;
        break;
      }
      case 2: {
        variant19 = 2;
        break;
      }
      case 3: {
        variant19 = 3;
        break;
      }
      case 4: {
        variant19 = 4;
        break;
      }
      case 5: {
        variant19 = 5;
        break;
      }
    }
    option20 = 1;
    option21 = variant19;
  } else {
    option20 = 0;
    option21 = 0;
  }
  int32_t option27;
  int32_t option28;
  if ((main_axis_size).is_some) {
    const flutter_renderer_widget_main_axis_size_t *payload23 = &(main_axis_size).val;
    int32_t variant26;
    switch ((int32_t) (*payload23).tag) {
      case 0: {
        variant26 = 0;
        break;
      }
      case 1: {
        variant26 = 1;
        break;
      }
    }
    option27 = 1;
    option28 = variant26;
  } else {
    option27 = 0;
    option28 = 0;
  }
  int32_t option34;
  int32_t option35;
  if ((text_direction).is_some) {
    const flutter_renderer_widget_text_direction_t *payload30 = &(text_direction).val;
    int32_t variant33;
    switch ((int32_t) (*payload30).tag) {
      case 0: {
        variant33 = 0;
        break;
      }
      case 1: {
        variant33 = 1;
        break;
      }
    }
    option34 = 1;
    option35 = variant33;
  } else {
    option34 = 0;
    option35 = 0;
  }
  int32_t option41;
  int32_t option42;
  if ((text_baseline).is_some) {
    const flutter_renderer_widget_text_baseline_t *payload37 = &(text_baseline).val;
    int32_t variant40;
    switch ((int32_t) (*payload37).tag) {
      case 0: {
        variant40 = 0;
        break;
      }
      case 1: {
        variant40 = 1;
        break;
      }
    }
    option41 = 1;
    option42 = variant40;
  } else {
    option41 = 0;
    option42 = 0;
  }
  int32_t option48;
  int32_t option49;
  if ((vertical_direction).is_some) {
    const flutter_renderer_widget_vertical_direction_t *payload44 = &(vertical_direction).val;
    int32_t variant47;
    switch ((int32_t) (*payload44).tag) {
      case 0: {
        variant47 = 0;
        break;
      }
      case 1: {
        variant47 = 1;
        break;
      }
    }
    option48 = 1;
    option49 = variant47;
  } else {
    option48 = 0;
    option49 = 0;
  }
  int32_t ret = __wasm_import_flutter_renderer_widget_constructor_col((uint8_t *) (*children).ptr, (*children).len, option, option10, option20, option21, option27, option28, option34, option35, option41, option42, option48, option49);
  return (flutter_renderer_widget_own_col_t) { ret };
}

flutter_renderer_widget_own_text_t flutter_renderer_widget_constructor_text(plugin_string_t *data) {
  int32_t ret = __wasm_import_flutter_renderer_widget_constructor_text((uint8_t *) (*data).ptr, (*data).len);
  return (flutter_renderer_widget_own_text_t) { ret };
}

flutter_renderer_widget_own_text_rich_t flutter_renderer_widget_constructor_text_rich(void) {
  int32_t ret = __wasm_import_flutter_renderer_widget_constructor_text_rich();
  return (flutter_renderer_widget_own_text_rich_t) { ret };
}

bool flutter_renderer_renderer_method_renderer_render(flutter_renderer_renderer_borrow_renderer_t self, flutter_renderer_renderer_widget_t *widget, flutter_renderer_renderer_error_t *ret) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  int32_t variant;
  int32_t variant3;
  switch ((int32_t) (*widget).tag) {
    case 0: {
      const flutter_renderer_widget_own_col_t *payload = &(*widget).val.col;
      variant = 0;
      variant3 = (*payload).__handle;
      break;
    }
    case 1: {
      const flutter_renderer_widget_own_row_t *payload0 = &(*widget).val.row;
      variant = 1;
      variant3 = (*payload0).__handle;
      break;
    }
    case 2: {
      const flutter_renderer_widget_own_text_t *payload1 = &(*widget).val.text;
      variant = 2;
      variant3 = (*payload1).__handle;
      break;
    }
    case 3: {
      const flutter_renderer_widget_own_text_rich_t *payload2 = &(*widget).val.text_rich;
      variant = 3;
      variant3 = (*payload2).__handle;
      break;
    }
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_flutter_renderer_renderer_method_renderer_render((self).__handle, variant, variant3, ptr);
  flutter_renderer_renderer_option_error_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      flutter_renderer_renderer_error_t variant4;
      variant4.tag = (int32_t) *((uint8_t*) (ptr + 1));
      switch ((int32_t) variant4.tag) {
        case 0: {
          break;
        }
      }

      option.val = variant4;
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

__attribute__((__export_name__("run")))
uint8_t * __wasm_export_plugin_run(int32_t arg) {
  plugin_error_t val;
  bool ret = plugin_run((plugin_own_renderer_t) { arg }, &val);

  plugin_option_error_t ret0;
  ret0.is_some = ret;
  ret0.val = val;
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret0).is_some) {
    const plugin_error_t *payload1 = &(ret0).val;
    *((int8_t*)(ptr + 0)) = 1;
    switch ((int32_t) (*payload1).tag) {
      case 0: {
        *((int8_t*)(ptr + 1)) = 0;
        break;
      }
    }
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_plugin(void);
void __component_type_object_force_link_plugin_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_plugin();
}
