// Generated by `wit-bindgen` 0.27.0. DO NOT EDIT!
#ifndef __BINDINGS_PLUGIN_H
#define __BINDINGS_PLUGIN_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct plugin_string_t {
  uint8_t*ptr;
  size_t len;
} plugin_string_t;

typedef struct flutter_renderer_alignment_own_alignment_t {
  int32_t __handle;
} flutter_renderer_alignment_own_alignment_t;

typedef struct flutter_renderer_alignment_borrow_alignment_t {
  int32_t __handle;
} flutter_renderer_alignment_borrow_alignment_t;

typedef struct flutter_renderer_alignment_own_alignment_directional_t {
  int32_t __handle;
} flutter_renderer_alignment_own_alignment_directional_t;

typedef struct flutter_renderer_alignment_borrow_alignment_directional_t {
  int32_t __handle;
} flutter_renderer_alignment_borrow_alignment_directional_t;

typedef struct flutter_renderer_alignment_alignment_geometry_t {
  uint8_t tag;
  union {
    flutter_renderer_alignment_own_alignment_t     alignment;
    flutter_renderer_alignment_own_alignment_directional_t     alignment_directional;
  } val;
} flutter_renderer_alignment_alignment_geometry_t;

#define FLUTTER_RENDERER_ALIGNMENT_ALIGNMENT_GEOMETRY_ALIGNMENT 0
#define FLUTTER_RENDERER_ALIGNMENT_ALIGNMENT_GEOMETRY_ALIGNMENT_DIRECTIONAL 1

typedef struct flutter_renderer_enums_main_axis_alignment_t {
  uint8_t tag;
} flutter_renderer_enums_main_axis_alignment_t;

#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_START 0
#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_END 1
#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_CENTER 2
#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_SPACE_BETWEEN 3
#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_SPACE_AROUND 4
#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_SPACE_EVENLY 5

typedef struct flutter_renderer_enums_text_direction_t {
  uint8_t tag;
} flutter_renderer_enums_text_direction_t;

#define FLUTTER_RENDERER_ENUMS_TEXT_DIRECTION_RTL 0
#define FLUTTER_RENDERER_ENUMS_TEXT_DIRECTION_LTR 1

typedef struct flutter_renderer_enums_vertical_direction_t {
  uint8_t tag;
} flutter_renderer_enums_vertical_direction_t;

#define FLUTTER_RENDERER_ENUMS_VERTICAL_DIRECTION_UP 0
#define FLUTTER_RENDERER_ENUMS_VERTICAL_DIRECTION_DOWN 1

typedef struct flutter_renderer_enums_main_axis_size_t {
  uint8_t tag;
} flutter_renderer_enums_main_axis_size_t;

#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_SIZE_MIN 0
#define FLUTTER_RENDERER_ENUMS_MAIN_AXIS_SIZE_MAX 1

typedef struct flutter_renderer_enums_text_baseline_t {
  uint8_t tag;
} flutter_renderer_enums_text_baseline_t;

#define FLUTTER_RENDERER_ENUMS_TEXT_BASELINE_ALPHABETIC 0
#define FLUTTER_RENDERER_ENUMS_TEXT_BASELINE_IDEOGRAPHIC 1

typedef struct flutter_renderer_enums_cross_axis_alignment_t {
  uint8_t tag;
} flutter_renderer_enums_cross_axis_alignment_t;

#define FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_START 0
#define FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_END 1
#define FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_CENTER 2
#define FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_STRETCH 3
#define FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_BASELINE 4

typedef flutter_renderer_alignment_alignment_geometry_t flutter_renderer_widget_alignment_geometry_t;

typedef flutter_renderer_enums_cross_axis_alignment_t flutter_renderer_widget_cross_axis_alignment_t;

typedef flutter_renderer_enums_main_axis_alignment_t flutter_renderer_widget_main_axis_alignment_t;

typedef flutter_renderer_enums_main_axis_size_t flutter_renderer_widget_main_axis_size_t;

typedef flutter_renderer_enums_text_direction_t flutter_renderer_widget_text_direction_t;

typedef flutter_renderer_enums_text_baseline_t flutter_renderer_widget_text_baseline_t;

typedef flutter_renderer_enums_vertical_direction_t flutter_renderer_widget_vertical_direction_t;

typedef struct flutter_renderer_widget_own_row_t {
  int32_t __handle;
} flutter_renderer_widget_own_row_t;

typedef struct flutter_renderer_widget_borrow_row_t {
  int32_t __handle;
} flutter_renderer_widget_borrow_row_t;

typedef struct flutter_renderer_widget_own_col_t {
  int32_t __handle;
} flutter_renderer_widget_own_col_t;

typedef struct flutter_renderer_widget_borrow_col_t {
  int32_t __handle;
} flutter_renderer_widget_borrow_col_t;

typedef struct flutter_renderer_widget_own_text_t {
  int32_t __handle;
} flutter_renderer_widget_own_text_t;

typedef struct flutter_renderer_widget_borrow_text_t {
  int32_t __handle;
} flutter_renderer_widget_borrow_text_t;

typedef struct flutter_renderer_widget_own_text_rich_t {
  int32_t __handle;
} flutter_renderer_widget_own_text_rich_t;

typedef struct flutter_renderer_widget_borrow_text_rich_t {
  int32_t __handle;
} flutter_renderer_widget_borrow_text_rich_t;

typedef struct flutter_renderer_widget_widget_t {
  uint8_t tag;
  union {
    flutter_renderer_widget_own_col_t     col;
    flutter_renderer_widget_own_row_t     row;
    flutter_renderer_widget_own_text_t     text;
    flutter_renderer_widget_own_text_rich_t     text_rich;
  } val;
} flutter_renderer_widget_widget_t;

#define FLUTTER_RENDERER_WIDGET_WIDGET_COL 0
#define FLUTTER_RENDERER_WIDGET_WIDGET_ROW 1
#define FLUTTER_RENDERER_WIDGET_WIDGET_TEXT 2
#define FLUTTER_RENDERER_WIDGET_WIDGET_TEXT_RICH 3

typedef struct {
  flutter_renderer_widget_widget_t *ptr;
  size_t len;
} flutter_renderer_widget_list_widget_t;

typedef struct {
  bool is_some;
  flutter_renderer_widget_cross_axis_alignment_t val;
} flutter_renderer_widget_option_cross_axis_alignment_t;

typedef struct {
  bool is_some;
  flutter_renderer_widget_main_axis_alignment_t val;
} flutter_renderer_widget_option_main_axis_alignment_t;

typedef struct {
  bool is_some;
  flutter_renderer_widget_main_axis_size_t val;
} flutter_renderer_widget_option_main_axis_size_t;

typedef struct {
  bool is_some;
  flutter_renderer_widget_text_direction_t val;
} flutter_renderer_widget_option_text_direction_t;

typedef struct {
  bool is_some;
  flutter_renderer_widget_text_baseline_t val;
} flutter_renderer_widget_option_text_baseline_t;

typedef struct {
  bool is_some;
  flutter_renderer_widget_vertical_direction_t val;
} flutter_renderer_widget_option_vertical_direction_t;

typedef flutter_renderer_widget_widget_t flutter_renderer_renderer_widget_t;

typedef struct flutter_renderer_renderer_error_t {
  uint8_t tag;
} flutter_renderer_renderer_error_t;

#define FLUTTER_RENDERER_RENDERER_ERROR_COMMON 0

typedef struct flutter_renderer_renderer_own_renderer_t {
  int32_t __handle;
} flutter_renderer_renderer_own_renderer_t;

typedef struct flutter_renderer_renderer_borrow_renderer_t {
  int32_t __handle;
} flutter_renderer_renderer_borrow_renderer_t;

typedef struct {
  bool is_some;
  flutter_renderer_renderer_error_t val;
} flutter_renderer_renderer_option_error_t;

typedef flutter_renderer_renderer_error_t plugin_error_t;

typedef flutter_renderer_renderer_own_renderer_t plugin_own_renderer_t;

typedef struct {
  bool is_some;
  plugin_error_t val;
} plugin_option_error_t;

// Imported Functions from `flutter:renderer/alignment`
extern flutter_renderer_alignment_own_alignment_t flutter_renderer_alignment_constructor_alignment(double start, double y);
extern flutter_renderer_alignment_own_alignment_directional_t flutter_renderer_alignment_constructor_alignment_directional(double start, double y);

// Imported Functions from `flutter:renderer/widget`
extern flutter_renderer_widget_own_row_t flutter_renderer_widget_constructor_row(flutter_renderer_widget_list_widget_t *children, flutter_renderer_widget_cross_axis_alignment_t *maybe_cross_axis_alignment, flutter_renderer_widget_main_axis_alignment_t *maybe_main_axis_alignment, flutter_renderer_widget_main_axis_size_t *maybe_main_axis_size, flutter_renderer_widget_text_direction_t *maybe_text_direction, flutter_renderer_widget_text_baseline_t *maybe_text_baseline, flutter_renderer_widget_vertical_direction_t *maybe_vertical_direction);
extern flutter_renderer_widget_own_col_t flutter_renderer_widget_constructor_col(flutter_renderer_widget_list_widget_t *children, flutter_renderer_widget_cross_axis_alignment_t *maybe_cross_axis_alignment, flutter_renderer_widget_main_axis_alignment_t *maybe_main_axis_alignment, flutter_renderer_widget_main_axis_size_t *maybe_main_axis_size, flutter_renderer_widget_text_direction_t *maybe_text_direction, flutter_renderer_widget_text_baseline_t *maybe_text_baseline, flutter_renderer_widget_vertical_direction_t *maybe_vertical_direction);
extern flutter_renderer_widget_own_text_t flutter_renderer_widget_constructor_text(plugin_string_t *data);
// TODO: rich
extern flutter_renderer_widget_own_text_rich_t flutter_renderer_widget_constructor_text_rich(void);

// Imported Functions from `flutter:renderer/renderer`
extern bool flutter_renderer_renderer_method_renderer_render(flutter_renderer_renderer_borrow_renderer_t self, flutter_renderer_renderer_widget_t *widget, flutter_renderer_renderer_error_t *ret);

// Exported Functions from `plugin`
bool plugin_run(plugin_own_renderer_t renderer, plugin_error_t *ret);

// Helper Functions

extern void flutter_renderer_alignment_alignment_drop_own(flutter_renderer_alignment_own_alignment_t handle);

extern flutter_renderer_alignment_borrow_alignment_t flutter_renderer_alignment_borrow_alignment(flutter_renderer_alignment_own_alignment_t handle);

extern void flutter_renderer_alignment_alignment_directional_drop_own(flutter_renderer_alignment_own_alignment_directional_t handle);

extern flutter_renderer_alignment_borrow_alignment_directional_t flutter_renderer_alignment_borrow_alignment_directional(flutter_renderer_alignment_own_alignment_directional_t handle);

void flutter_renderer_alignment_alignment_geometry_free(flutter_renderer_alignment_alignment_geometry_t *ptr);

void flutter_renderer_enums_main_axis_alignment_free(flutter_renderer_enums_main_axis_alignment_t *ptr);

void flutter_renderer_enums_text_direction_free(flutter_renderer_enums_text_direction_t *ptr);

void flutter_renderer_enums_vertical_direction_free(flutter_renderer_enums_vertical_direction_t *ptr);

void flutter_renderer_enums_main_axis_size_free(flutter_renderer_enums_main_axis_size_t *ptr);

void flutter_renderer_enums_text_baseline_free(flutter_renderer_enums_text_baseline_t *ptr);

void flutter_renderer_enums_cross_axis_alignment_free(flutter_renderer_enums_cross_axis_alignment_t *ptr);

void flutter_renderer_widget_alignment_geometry_free(flutter_renderer_widget_alignment_geometry_t *ptr);

void flutter_renderer_widget_cross_axis_alignment_free(flutter_renderer_widget_cross_axis_alignment_t *ptr);

void flutter_renderer_widget_main_axis_alignment_free(flutter_renderer_widget_main_axis_alignment_t *ptr);

void flutter_renderer_widget_main_axis_size_free(flutter_renderer_widget_main_axis_size_t *ptr);

void flutter_renderer_widget_text_direction_free(flutter_renderer_widget_text_direction_t *ptr);

void flutter_renderer_widget_text_baseline_free(flutter_renderer_widget_text_baseline_t *ptr);

void flutter_renderer_widget_vertical_direction_free(flutter_renderer_widget_vertical_direction_t *ptr);

extern void flutter_renderer_widget_row_drop_own(flutter_renderer_widget_own_row_t handle);

extern flutter_renderer_widget_borrow_row_t flutter_renderer_widget_borrow_row(flutter_renderer_widget_own_row_t handle);

extern void flutter_renderer_widget_col_drop_own(flutter_renderer_widget_own_col_t handle);

extern flutter_renderer_widget_borrow_col_t flutter_renderer_widget_borrow_col(flutter_renderer_widget_own_col_t handle);

extern void flutter_renderer_widget_text_drop_own(flutter_renderer_widget_own_text_t handle);

extern flutter_renderer_widget_borrow_text_t flutter_renderer_widget_borrow_text(flutter_renderer_widget_own_text_t handle);

extern void flutter_renderer_widget_text_rich_drop_own(flutter_renderer_widget_own_text_rich_t handle);

extern flutter_renderer_widget_borrow_text_rich_t flutter_renderer_widget_borrow_text_rich(flutter_renderer_widget_own_text_rich_t handle);

void flutter_renderer_widget_widget_free(flutter_renderer_widget_widget_t *ptr);

void flutter_renderer_widget_list_widget_free(flutter_renderer_widget_list_widget_t *ptr);

void flutter_renderer_widget_option_cross_axis_alignment_free(flutter_renderer_widget_option_cross_axis_alignment_t *ptr);

void flutter_renderer_widget_option_main_axis_alignment_free(flutter_renderer_widget_option_main_axis_alignment_t *ptr);

void flutter_renderer_widget_option_main_axis_size_free(flutter_renderer_widget_option_main_axis_size_t *ptr);

void flutter_renderer_widget_option_text_direction_free(flutter_renderer_widget_option_text_direction_t *ptr);

void flutter_renderer_widget_option_text_baseline_free(flutter_renderer_widget_option_text_baseline_t *ptr);

void flutter_renderer_widget_option_vertical_direction_free(flutter_renderer_widget_option_vertical_direction_t *ptr);

void flutter_renderer_renderer_widget_free(flutter_renderer_renderer_widget_t *ptr);

void flutter_renderer_renderer_error_free(flutter_renderer_renderer_error_t *ptr);

extern void flutter_renderer_renderer_renderer_drop_own(flutter_renderer_renderer_own_renderer_t handle);

extern flutter_renderer_renderer_borrow_renderer_t flutter_renderer_renderer_borrow_renderer(flutter_renderer_renderer_own_renderer_t handle);

void flutter_renderer_renderer_option_error_free(flutter_renderer_renderer_option_error_t *ptr);

void plugin_error_free(plugin_error_t *ptr);

void plugin_option_error_free(plugin_option_error_t *ptr);

// Transfers ownership of `s` into the string `ret`
void plugin_string_set(plugin_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void plugin_string_dup(plugin_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void plugin_string_free(plugin_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
