// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Binding for plugin
class Plugin {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  Plugin(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  Plugin.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  flutter_renderer_alignment_own_alignment_t
      flutter_renderer_alignment_constructor_alignment(
    double start,
    double y,
  ) {
    return _flutter_renderer_alignment_constructor_alignment(
      start,
      y,
    );
  }

  late final _flutter_renderer_alignment_constructor_alignmentPtr = _lookup<
      ffi.NativeFunction<
          flutter_renderer_alignment_own_alignment_t Function(ffi.Double,
              ffi.Double)>>('flutter_renderer_alignment_constructor_alignment');
  late final _flutter_renderer_alignment_constructor_alignment =
      _flutter_renderer_alignment_constructor_alignmentPtr.asFunction<
          flutter_renderer_alignment_own_alignment_t Function(
              double, double)>();

  flutter_renderer_alignment_own_alignment_directional_t
      flutter_renderer_alignment_constructor_alignment_directional(
    double start,
    double y,
  ) {
    return _flutter_renderer_alignment_constructor_alignment_directional(
      start,
      y,
    );
  }

  late final _flutter_renderer_alignment_constructor_alignment_directionalPtr =
      _lookup<
              ffi.NativeFunction<
                  flutter_renderer_alignment_own_alignment_directional_t
                      Function(ffi.Double, ffi.Double)>>(
          'flutter_renderer_alignment_constructor_alignment_directional');
  late final _flutter_renderer_alignment_constructor_alignment_directional =
      _flutter_renderer_alignment_constructor_alignment_directionalPtr
          .asFunction<
              flutter_renderer_alignment_own_alignment_directional_t Function(
                  double, double)>();

  flutter_renderer_widget_own_row_t flutter_renderer_widget_constructor_row(
    ffi.Pointer<flutter_renderer_widget_list_widget_t> children,
    ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t>
        maybe_cross_axis_alignment,
    ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>
        maybe_main_axis_alignment,
    ffi.Pointer<flutter_renderer_widget_main_axis_size_t> maybe_main_axis_size,
    ffi.Pointer<flutter_renderer_widget_text_direction_t> maybe_text_direction,
    ffi.Pointer<flutter_renderer_widget_text_baseline_t> maybe_text_baseline,
    ffi.Pointer<flutter_renderer_widget_vertical_direction_t>
        maybe_vertical_direction,
  ) {
    return _flutter_renderer_widget_constructor_row(
      children,
      maybe_cross_axis_alignment,
      maybe_main_axis_alignment,
      maybe_main_axis_size,
      maybe_text_direction,
      maybe_text_baseline,
      maybe_vertical_direction,
    );
  }

  late final _flutter_renderer_widget_constructor_rowPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_widget_own_row_t Function(
                  ffi.Pointer<flutter_renderer_widget_list_widget_t>,
                  ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t>,
                  ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>,
                  ffi.Pointer<flutter_renderer_widget_main_axis_size_t>,
                  ffi.Pointer<flutter_renderer_widget_text_direction_t>,
                  ffi.Pointer<flutter_renderer_widget_text_baseline_t>,
                  ffi.Pointer<flutter_renderer_widget_vertical_direction_t>)>>(
      'flutter_renderer_widget_constructor_row');
  late final _flutter_renderer_widget_constructor_row =
      _flutter_renderer_widget_constructor_rowPtr.asFunction<
          flutter_renderer_widget_own_row_t Function(
              ffi.Pointer<flutter_renderer_widget_list_widget_t>,
              ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t>,
              ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>,
              ffi.Pointer<flutter_renderer_widget_main_axis_size_t>,
              ffi.Pointer<flutter_renderer_widget_text_direction_t>,
              ffi.Pointer<flutter_renderer_widget_text_baseline_t>,
              ffi.Pointer<flutter_renderer_widget_vertical_direction_t>)>();

  flutter_renderer_widget_own_col_t flutter_renderer_widget_constructor_col(
    ffi.Pointer<flutter_renderer_widget_list_widget_t> children,
    ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t>
        maybe_cross_axis_alignment,
    ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>
        maybe_main_axis_alignment,
    ffi.Pointer<flutter_renderer_widget_main_axis_size_t> maybe_main_axis_size,
    ffi.Pointer<flutter_renderer_widget_text_direction_t> maybe_text_direction,
    ffi.Pointer<flutter_renderer_widget_text_baseline_t> maybe_text_baseline,
    ffi.Pointer<flutter_renderer_widget_vertical_direction_t>
        maybe_vertical_direction,
  ) {
    return _flutter_renderer_widget_constructor_col(
      children,
      maybe_cross_axis_alignment,
      maybe_main_axis_alignment,
      maybe_main_axis_size,
      maybe_text_direction,
      maybe_text_baseline,
      maybe_vertical_direction,
    );
  }

  late final _flutter_renderer_widget_constructor_colPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_widget_own_col_t Function(
                  ffi.Pointer<flutter_renderer_widget_list_widget_t>,
                  ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t>,
                  ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>,
                  ffi.Pointer<flutter_renderer_widget_main_axis_size_t>,
                  ffi.Pointer<flutter_renderer_widget_text_direction_t>,
                  ffi.Pointer<flutter_renderer_widget_text_baseline_t>,
                  ffi.Pointer<flutter_renderer_widget_vertical_direction_t>)>>(
      'flutter_renderer_widget_constructor_col');
  late final _flutter_renderer_widget_constructor_col =
      _flutter_renderer_widget_constructor_colPtr.asFunction<
          flutter_renderer_widget_own_col_t Function(
              ffi.Pointer<flutter_renderer_widget_list_widget_t>,
              ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t>,
              ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>,
              ffi.Pointer<flutter_renderer_widget_main_axis_size_t>,
              ffi.Pointer<flutter_renderer_widget_text_direction_t>,
              ffi.Pointer<flutter_renderer_widget_text_baseline_t>,
              ffi.Pointer<flutter_renderer_widget_vertical_direction_t>)>();

  flutter_renderer_widget_own_text_t flutter_renderer_widget_constructor_text(
    ffi.Pointer<plugin_string_t> data,
  ) {
    return _flutter_renderer_widget_constructor_text(
      data,
    );
  }

  late final _flutter_renderer_widget_constructor_textPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_widget_own_text_t Function(
                  ffi.Pointer<plugin_string_t>)>>(
      'flutter_renderer_widget_constructor_text');
  late final _flutter_renderer_widget_constructor_text =
      _flutter_renderer_widget_constructor_textPtr.asFunction<
          flutter_renderer_widget_own_text_t Function(
              ffi.Pointer<plugin_string_t>)>();

  flutter_renderer_widget_own_text_rich_t
      flutter_renderer_widget_constructor_text_rich() {
    return _flutter_renderer_widget_constructor_text_rich();
  }

  late final _flutter_renderer_widget_constructor_text_richPtr = _lookup<
          ffi
          .NativeFunction<flutter_renderer_widget_own_text_rich_t Function()>>(
      'flutter_renderer_widget_constructor_text_rich');
  late final _flutter_renderer_widget_constructor_text_rich =
      _flutter_renderer_widget_constructor_text_richPtr
          .asFunction<flutter_renderer_widget_own_text_rich_t Function()>();

  bool flutter_renderer_renderer_method_renderer_render(
    flutter_renderer_renderer_borrow_renderer_t self,
    ffi.Pointer<flutter_renderer_renderer_widget_t> widget,
    ffi.Pointer<flutter_renderer_renderer_error_t> ret,
  ) {
    return _flutter_renderer_renderer_method_renderer_render(
      self,
      widget,
      ret,
    );
  }

  late final _flutter_renderer_renderer_method_renderer_renderPtr = _lookup<
          ffi.NativeFunction<
              ffi.Bool Function(
                  flutter_renderer_renderer_borrow_renderer_t,
                  ffi.Pointer<flutter_renderer_renderer_widget_t>,
                  ffi.Pointer<flutter_renderer_renderer_error_t>)>>(
      'flutter_renderer_renderer_method_renderer_render');
  late final _flutter_renderer_renderer_method_renderer_render =
      _flutter_renderer_renderer_method_renderer_renderPtr.asFunction<
          bool Function(
              flutter_renderer_renderer_borrow_renderer_t,
              ffi.Pointer<flutter_renderer_renderer_widget_t>,
              ffi.Pointer<flutter_renderer_renderer_error_t>)>();

  bool plugin_run(
    plugin_own_renderer_t renderer,
    ffi.Pointer<plugin_error_t> ret,
  ) {
    return _plugin_run(
      renderer,
      ret,
    );
  }

  late final _plugin_runPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(plugin_own_renderer_t,
              ffi.Pointer<plugin_error_t>)>>('plugin_run');
  late final _plugin_run = _plugin_runPtr.asFunction<
      bool Function(plugin_own_renderer_t, ffi.Pointer<plugin_error_t>)>();

  void flutter_renderer_alignment_alignment_drop_own(
    flutter_renderer_alignment_own_alignment_t handle,
  ) {
    return _flutter_renderer_alignment_alignment_drop_own(
      handle,
    );
  }

  late final _flutter_renderer_alignment_alignment_drop_ownPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(flutter_renderer_alignment_own_alignment_t)>>(
      'flutter_renderer_alignment_alignment_drop_own');
  late final _flutter_renderer_alignment_alignment_drop_own =
      _flutter_renderer_alignment_alignment_drop_ownPtr.asFunction<
          void Function(flutter_renderer_alignment_own_alignment_t)>();

  flutter_renderer_alignment_borrow_alignment_t
      flutter_renderer_alignment_borrow_alignment(
    flutter_renderer_alignment_own_alignment_t handle,
  ) {
    return _flutter_renderer_alignment_borrow_alignment(
      handle,
    );
  }

  late final _flutter_renderer_alignment_borrow_alignmentPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_alignment_borrow_alignment_t Function(
                  flutter_renderer_alignment_own_alignment_t)>>(
      'flutter_renderer_alignment_borrow_alignment');
  late final _flutter_renderer_alignment_borrow_alignment =
      _flutter_renderer_alignment_borrow_alignmentPtr.asFunction<
          flutter_renderer_alignment_borrow_alignment_t Function(
              flutter_renderer_alignment_own_alignment_t)>();

  void flutter_renderer_alignment_alignment_directional_drop_own(
    flutter_renderer_alignment_own_alignment_directional_t handle,
  ) {
    return _flutter_renderer_alignment_alignment_directional_drop_own(
      handle,
    );
  }

  late final _flutter_renderer_alignment_alignment_directional_drop_ownPtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Void Function(
                      flutter_renderer_alignment_own_alignment_directional_t)>>(
          'flutter_renderer_alignment_alignment_directional_drop_own');
  late final _flutter_renderer_alignment_alignment_directional_drop_own =
      _flutter_renderer_alignment_alignment_directional_drop_ownPtr.asFunction<
          void Function(
              flutter_renderer_alignment_own_alignment_directional_t)>();

  flutter_renderer_alignment_borrow_alignment_directional_t
      flutter_renderer_alignment_borrow_alignment_directional(
    flutter_renderer_alignment_own_alignment_directional_t handle,
  ) {
    return _flutter_renderer_alignment_borrow_alignment_directional(
      handle,
    );
  }

  late final _flutter_renderer_alignment_borrow_alignment_directionalPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_alignment_borrow_alignment_directional_t Function(
                  flutter_renderer_alignment_own_alignment_directional_t)>>(
      'flutter_renderer_alignment_borrow_alignment_directional');
  late final _flutter_renderer_alignment_borrow_alignment_directional =
      _flutter_renderer_alignment_borrow_alignment_directionalPtr.asFunction<
          flutter_renderer_alignment_borrow_alignment_directional_t Function(
              flutter_renderer_alignment_own_alignment_directional_t)>();

  void flutter_renderer_alignment_alignment_geometry_free(
    ffi.Pointer<flutter_renderer_alignment_alignment_geometry_t> ptr,
  ) {
    return _flutter_renderer_alignment_alignment_geometry_free(
      ptr,
    );
  }

  late final _flutter_renderer_alignment_alignment_geometry_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_alignment_alignment_geometry_t>)>>(
      'flutter_renderer_alignment_alignment_geometry_free');
  late final _flutter_renderer_alignment_alignment_geometry_free =
      _flutter_renderer_alignment_alignment_geometry_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_alignment_alignment_geometry_t>)>();

  void flutter_renderer_enums_main_axis_alignment_free(
    ffi.Pointer<flutter_renderer_enums_main_axis_alignment_t> ptr,
  ) {
    return _flutter_renderer_enums_main_axis_alignment_free(
      ptr,
    );
  }

  late final _flutter_renderer_enums_main_axis_alignment_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_enums_main_axis_alignment_t>)>>(
      'flutter_renderer_enums_main_axis_alignment_free');
  late final _flutter_renderer_enums_main_axis_alignment_free =
      _flutter_renderer_enums_main_axis_alignment_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_enums_main_axis_alignment_t>)>();

  void flutter_renderer_enums_text_direction_free(
    ffi.Pointer<flutter_renderer_enums_text_direction_t> ptr,
  ) {
    return _flutter_renderer_enums_text_direction_free(
      ptr,
    );
  }

  late final _flutter_renderer_enums_text_direction_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_enums_text_direction_t>)>>(
      'flutter_renderer_enums_text_direction_free');
  late final _flutter_renderer_enums_text_direction_free =
      _flutter_renderer_enums_text_direction_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_enums_text_direction_t>)>();

  void flutter_renderer_enums_vertical_direction_free(
    ffi.Pointer<flutter_renderer_enums_vertical_direction_t> ptr,
  ) {
    return _flutter_renderer_enums_vertical_direction_free(
      ptr,
    );
  }

  late final _flutter_renderer_enums_vertical_direction_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_enums_vertical_direction_t>)>>(
      'flutter_renderer_enums_vertical_direction_free');
  late final _flutter_renderer_enums_vertical_direction_free =
      _flutter_renderer_enums_vertical_direction_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_enums_vertical_direction_t>)>();

  void flutter_renderer_enums_main_axis_size_free(
    ffi.Pointer<flutter_renderer_enums_main_axis_size_t> ptr,
  ) {
    return _flutter_renderer_enums_main_axis_size_free(
      ptr,
    );
  }

  late final _flutter_renderer_enums_main_axis_size_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_enums_main_axis_size_t>)>>(
      'flutter_renderer_enums_main_axis_size_free');
  late final _flutter_renderer_enums_main_axis_size_free =
      _flutter_renderer_enums_main_axis_size_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_enums_main_axis_size_t>)>();

  void flutter_renderer_enums_text_baseline_free(
    ffi.Pointer<flutter_renderer_enums_text_baseline_t> ptr,
  ) {
    return _flutter_renderer_enums_text_baseline_free(
      ptr,
    );
  }

  late final _flutter_renderer_enums_text_baseline_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_enums_text_baseline_t>)>>(
      'flutter_renderer_enums_text_baseline_free');
  late final _flutter_renderer_enums_text_baseline_free =
      _flutter_renderer_enums_text_baseline_freePtr.asFunction<
          void Function(ffi.Pointer<flutter_renderer_enums_text_baseline_t>)>();

  void flutter_renderer_enums_cross_axis_alignment_free(
    ffi.Pointer<flutter_renderer_enums_cross_axis_alignment_t> ptr,
  ) {
    return _flutter_renderer_enums_cross_axis_alignment_free(
      ptr,
    );
  }

  late final _flutter_renderer_enums_cross_axis_alignment_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_enums_cross_axis_alignment_t>)>>(
      'flutter_renderer_enums_cross_axis_alignment_free');
  late final _flutter_renderer_enums_cross_axis_alignment_free =
      _flutter_renderer_enums_cross_axis_alignment_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_enums_cross_axis_alignment_t>)>();

  void flutter_renderer_widget_alignment_geometry_free(
    ffi.Pointer<flutter_renderer_widget_alignment_geometry_t> ptr,
  ) {
    return _flutter_renderer_widget_alignment_geometry_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_alignment_geometry_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_alignment_geometry_t>)>>(
      'flutter_renderer_widget_alignment_geometry_free');
  late final _flutter_renderer_widget_alignment_geometry_free =
      _flutter_renderer_widget_alignment_geometry_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_alignment_geometry_t>)>();

  void flutter_renderer_widget_cross_axis_alignment_free(
    ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t> ptr,
  ) {
    return _flutter_renderer_widget_cross_axis_alignment_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_cross_axis_alignment_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_widget_cross_axis_alignment_t>)>>(
      'flutter_renderer_widget_cross_axis_alignment_free');
  late final _flutter_renderer_widget_cross_axis_alignment_free =
      _flutter_renderer_widget_cross_axis_alignment_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_cross_axis_alignment_t>)>();

  void flutter_renderer_widget_main_axis_alignment_free(
    ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t> ptr,
  ) {
    return _flutter_renderer_widget_main_axis_alignment_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_main_axis_alignment_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>)>>(
      'flutter_renderer_widget_main_axis_alignment_free');
  late final _flutter_renderer_widget_main_axis_alignment_free =
      _flutter_renderer_widget_main_axis_alignment_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_main_axis_alignment_t>)>();

  void flutter_renderer_widget_main_axis_size_free(
    ffi.Pointer<flutter_renderer_widget_main_axis_size_t> ptr,
  ) {
    return _flutter_renderer_widget_main_axis_size_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_main_axis_size_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_main_axis_size_t>)>>(
      'flutter_renderer_widget_main_axis_size_free');
  late final _flutter_renderer_widget_main_axis_size_free =
      _flutter_renderer_widget_main_axis_size_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_main_axis_size_t>)>();

  void flutter_renderer_widget_text_direction_free(
    ffi.Pointer<flutter_renderer_widget_text_direction_t> ptr,
  ) {
    return _flutter_renderer_widget_text_direction_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_text_direction_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_text_direction_t>)>>(
      'flutter_renderer_widget_text_direction_free');
  late final _flutter_renderer_widget_text_direction_free =
      _flutter_renderer_widget_text_direction_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_text_direction_t>)>();

  void flutter_renderer_widget_text_baseline_free(
    ffi.Pointer<flutter_renderer_widget_text_baseline_t> ptr,
  ) {
    return _flutter_renderer_widget_text_baseline_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_text_baseline_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_text_baseline_t>)>>(
      'flutter_renderer_widget_text_baseline_free');
  late final _flutter_renderer_widget_text_baseline_free =
      _flutter_renderer_widget_text_baseline_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_text_baseline_t>)>();

  void flutter_renderer_widget_vertical_direction_free(
    ffi.Pointer<flutter_renderer_widget_vertical_direction_t> ptr,
  ) {
    return _flutter_renderer_widget_vertical_direction_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_vertical_direction_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_vertical_direction_t>)>>(
      'flutter_renderer_widget_vertical_direction_free');
  late final _flutter_renderer_widget_vertical_direction_free =
      _flutter_renderer_widget_vertical_direction_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_vertical_direction_t>)>();

  void flutter_renderer_widget_row_drop_own(
    flutter_renderer_widget_own_row_t handle,
  ) {
    return _flutter_renderer_widget_row_drop_own(
      handle,
    );
  }

  late final _flutter_renderer_widget_row_drop_ownPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(flutter_renderer_widget_own_row_t)>>(
      'flutter_renderer_widget_row_drop_own');
  late final _flutter_renderer_widget_row_drop_own =
      _flutter_renderer_widget_row_drop_ownPtr
          .asFunction<void Function(flutter_renderer_widget_own_row_t)>();

  flutter_renderer_widget_borrow_row_t flutter_renderer_widget_borrow_row(
    flutter_renderer_widget_own_row_t handle,
  ) {
    return _flutter_renderer_widget_borrow_row(
      handle,
    );
  }

  late final _flutter_renderer_widget_borrow_rowPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_widget_borrow_row_t Function(
                  flutter_renderer_widget_own_row_t)>>(
      'flutter_renderer_widget_borrow_row');
  late final _flutter_renderer_widget_borrow_row =
      _flutter_renderer_widget_borrow_rowPtr.asFunction<
          flutter_renderer_widget_borrow_row_t Function(
              flutter_renderer_widget_own_row_t)>();

  void flutter_renderer_widget_col_drop_own(
    flutter_renderer_widget_own_col_t handle,
  ) {
    return _flutter_renderer_widget_col_drop_own(
      handle,
    );
  }

  late final _flutter_renderer_widget_col_drop_ownPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(flutter_renderer_widget_own_col_t)>>(
      'flutter_renderer_widget_col_drop_own');
  late final _flutter_renderer_widget_col_drop_own =
      _flutter_renderer_widget_col_drop_ownPtr
          .asFunction<void Function(flutter_renderer_widget_own_col_t)>();

  flutter_renderer_widget_borrow_col_t flutter_renderer_widget_borrow_col(
    flutter_renderer_widget_own_col_t handle,
  ) {
    return _flutter_renderer_widget_borrow_col(
      handle,
    );
  }

  late final _flutter_renderer_widget_borrow_colPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_widget_borrow_col_t Function(
                  flutter_renderer_widget_own_col_t)>>(
      'flutter_renderer_widget_borrow_col');
  late final _flutter_renderer_widget_borrow_col =
      _flutter_renderer_widget_borrow_colPtr.asFunction<
          flutter_renderer_widget_borrow_col_t Function(
              flutter_renderer_widget_own_col_t)>();

  void flutter_renderer_widget_text_drop_own(
    flutter_renderer_widget_own_text_t handle,
  ) {
    return _flutter_renderer_widget_text_drop_own(
      handle,
    );
  }

  late final _flutter_renderer_widget_text_drop_ownPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(flutter_renderer_widget_own_text_t)>>(
      'flutter_renderer_widget_text_drop_own');
  late final _flutter_renderer_widget_text_drop_own =
      _flutter_renderer_widget_text_drop_ownPtr
          .asFunction<void Function(flutter_renderer_widget_own_text_t)>();

  flutter_renderer_widget_borrow_text_t flutter_renderer_widget_borrow_text(
    flutter_renderer_widget_own_text_t handle,
  ) {
    return _flutter_renderer_widget_borrow_text(
      handle,
    );
  }

  late final _flutter_renderer_widget_borrow_textPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_widget_borrow_text_t Function(
                  flutter_renderer_widget_own_text_t)>>(
      'flutter_renderer_widget_borrow_text');
  late final _flutter_renderer_widget_borrow_text =
      _flutter_renderer_widget_borrow_textPtr.asFunction<
          flutter_renderer_widget_borrow_text_t Function(
              flutter_renderer_widget_own_text_t)>();

  void flutter_renderer_widget_text_rich_drop_own(
    flutter_renderer_widget_own_text_rich_t handle,
  ) {
    return _flutter_renderer_widget_text_rich_drop_own(
      handle,
    );
  }

  late final _flutter_renderer_widget_text_rich_drop_ownPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(flutter_renderer_widget_own_text_rich_t)>>(
      'flutter_renderer_widget_text_rich_drop_own');
  late final _flutter_renderer_widget_text_rich_drop_own =
      _flutter_renderer_widget_text_rich_drop_ownPtr
          .asFunction<void Function(flutter_renderer_widget_own_text_rich_t)>();

  flutter_renderer_widget_borrow_text_rich_t
      flutter_renderer_widget_borrow_text_rich(
    flutter_renderer_widget_own_text_rich_t handle,
  ) {
    return _flutter_renderer_widget_borrow_text_rich(
      handle,
    );
  }

  late final _flutter_renderer_widget_borrow_text_richPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_widget_borrow_text_rich_t Function(
                  flutter_renderer_widget_own_text_rich_t)>>(
      'flutter_renderer_widget_borrow_text_rich');
  late final _flutter_renderer_widget_borrow_text_rich =
      _flutter_renderer_widget_borrow_text_richPtr.asFunction<
          flutter_renderer_widget_borrow_text_rich_t Function(
              flutter_renderer_widget_own_text_rich_t)>();

  void flutter_renderer_widget_widget_free(
    ffi.Pointer<flutter_renderer_widget_widget_t> ptr,
  ) {
    return _flutter_renderer_widget_widget_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_widget_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_widget_t>)>>(
      'flutter_renderer_widget_widget_free');
  late final _flutter_renderer_widget_widget_free =
      _flutter_renderer_widget_widget_freePtr.asFunction<
          void Function(ffi.Pointer<flutter_renderer_widget_widget_t>)>();

  void flutter_renderer_widget_list_widget_free(
    ffi.Pointer<flutter_renderer_widget_list_widget_t> ptr,
  ) {
    return _flutter_renderer_widget_list_widget_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_list_widget_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_widget_list_widget_t>)>>(
      'flutter_renderer_widget_list_widget_free');
  late final _flutter_renderer_widget_list_widget_free =
      _flutter_renderer_widget_list_widget_freePtr.asFunction<
          void Function(ffi.Pointer<flutter_renderer_widget_list_widget_t>)>();

  void flutter_renderer_widget_option_cross_axis_alignment_free(
    ffi.Pointer<flutter_renderer_widget_option_cross_axis_alignment_t> ptr,
  ) {
    return _flutter_renderer_widget_option_cross_axis_alignment_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_option_cross_axis_alignment_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_widget_option_cross_axis_alignment_t>)>>(
      'flutter_renderer_widget_option_cross_axis_alignment_free');
  late final _flutter_renderer_widget_option_cross_axis_alignment_free =
      _flutter_renderer_widget_option_cross_axis_alignment_freePtr.asFunction<
          void Function(
              ffi.Pointer<
                  flutter_renderer_widget_option_cross_axis_alignment_t>)>();

  void flutter_renderer_widget_option_main_axis_alignment_free(
    ffi.Pointer<flutter_renderer_widget_option_main_axis_alignment_t> ptr,
  ) {
    return _flutter_renderer_widget_option_main_axis_alignment_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_option_main_axis_alignment_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_widget_option_main_axis_alignment_t>)>>(
      'flutter_renderer_widget_option_main_axis_alignment_free');
  late final _flutter_renderer_widget_option_main_axis_alignment_free =
      _flutter_renderer_widget_option_main_axis_alignment_freePtr.asFunction<
          void Function(
              ffi.Pointer<
                  flutter_renderer_widget_option_main_axis_alignment_t>)>();

  void flutter_renderer_widget_option_main_axis_size_free(
    ffi.Pointer<flutter_renderer_widget_option_main_axis_size_t> ptr,
  ) {
    return _flutter_renderer_widget_option_main_axis_size_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_option_main_axis_size_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_widget_option_main_axis_size_t>)>>(
      'flutter_renderer_widget_option_main_axis_size_free');
  late final _flutter_renderer_widget_option_main_axis_size_free =
      _flutter_renderer_widget_option_main_axis_size_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_option_main_axis_size_t>)>();

  void flutter_renderer_widget_option_text_direction_free(
    ffi.Pointer<flutter_renderer_widget_option_text_direction_t> ptr,
  ) {
    return _flutter_renderer_widget_option_text_direction_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_option_text_direction_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_widget_option_text_direction_t>)>>(
      'flutter_renderer_widget_option_text_direction_free');
  late final _flutter_renderer_widget_option_text_direction_free =
      _flutter_renderer_widget_option_text_direction_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_option_text_direction_t>)>();

  void flutter_renderer_widget_option_text_baseline_free(
    ffi.Pointer<flutter_renderer_widget_option_text_baseline_t> ptr,
  ) {
    return _flutter_renderer_widget_option_text_baseline_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_option_text_baseline_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_widget_option_text_baseline_t>)>>(
      'flutter_renderer_widget_option_text_baseline_free');
  late final _flutter_renderer_widget_option_text_baseline_free =
      _flutter_renderer_widget_option_text_baseline_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_widget_option_text_baseline_t>)>();

  void flutter_renderer_widget_option_vertical_direction_free(
    ffi.Pointer<flutter_renderer_widget_option_vertical_direction_t> ptr,
  ) {
    return _flutter_renderer_widget_option_vertical_direction_free(
      ptr,
    );
  }

  late final _flutter_renderer_widget_option_vertical_direction_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<
                      flutter_renderer_widget_option_vertical_direction_t>)>>(
      'flutter_renderer_widget_option_vertical_direction_free');
  late final _flutter_renderer_widget_option_vertical_direction_free =
      _flutter_renderer_widget_option_vertical_direction_freePtr.asFunction<
          void Function(
              ffi.Pointer<
                  flutter_renderer_widget_option_vertical_direction_t>)>();

  void flutter_renderer_renderer_widget_free(
    ffi.Pointer<flutter_renderer_renderer_widget_t> ptr,
  ) {
    return _flutter_renderer_renderer_widget_free(
      ptr,
    );
  }

  late final _flutter_renderer_renderer_widget_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_renderer_widget_t>)>>(
      'flutter_renderer_renderer_widget_free');
  late final _flutter_renderer_renderer_widget_free =
      _flutter_renderer_renderer_widget_freePtr.asFunction<
          void Function(ffi.Pointer<flutter_renderer_renderer_widget_t>)>();

  void flutter_renderer_renderer_error_free(
    ffi.Pointer<flutter_renderer_renderer_error_t> ptr,
  ) {
    return _flutter_renderer_renderer_error_free(
      ptr,
    );
  }

  late final _flutter_renderer_renderer_error_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_renderer_error_t>)>>(
      'flutter_renderer_renderer_error_free');
  late final _flutter_renderer_renderer_error_free =
      _flutter_renderer_renderer_error_freePtr.asFunction<
          void Function(ffi.Pointer<flutter_renderer_renderer_error_t>)>();

  void flutter_renderer_renderer_renderer_drop_own(
    flutter_renderer_renderer_own_renderer_t handle,
  ) {
    return _flutter_renderer_renderer_renderer_drop_own(
      handle,
    );
  }

  late final _flutter_renderer_renderer_renderer_drop_ownPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(flutter_renderer_renderer_own_renderer_t)>>(
      'flutter_renderer_renderer_renderer_drop_own');
  late final _flutter_renderer_renderer_renderer_drop_own =
      _flutter_renderer_renderer_renderer_drop_ownPtr.asFunction<
          void Function(flutter_renderer_renderer_own_renderer_t)>();

  flutter_renderer_renderer_borrow_renderer_t
      flutter_renderer_renderer_borrow_renderer(
    flutter_renderer_renderer_own_renderer_t handle,
  ) {
    return _flutter_renderer_renderer_borrow_renderer(
      handle,
    );
  }

  late final _flutter_renderer_renderer_borrow_rendererPtr = _lookup<
          ffi.NativeFunction<
              flutter_renderer_renderer_borrow_renderer_t Function(
                  flutter_renderer_renderer_own_renderer_t)>>(
      'flutter_renderer_renderer_borrow_renderer');
  late final _flutter_renderer_renderer_borrow_renderer =
      _flutter_renderer_renderer_borrow_rendererPtr.asFunction<
          flutter_renderer_renderer_borrow_renderer_t Function(
              flutter_renderer_renderer_own_renderer_t)>();

  void flutter_renderer_renderer_option_error_free(
    ffi.Pointer<flutter_renderer_renderer_option_error_t> ptr,
  ) {
    return _flutter_renderer_renderer_option_error_free(
      ptr,
    );
  }

  late final _flutter_renderer_renderer_option_error_freePtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Pointer<flutter_renderer_renderer_option_error_t>)>>(
      'flutter_renderer_renderer_option_error_free');
  late final _flutter_renderer_renderer_option_error_free =
      _flutter_renderer_renderer_option_error_freePtr.asFunction<
          void Function(
              ffi.Pointer<flutter_renderer_renderer_option_error_t>)>();

  void plugin_error_free(
    ffi.Pointer<plugin_error_t> ptr,
  ) {
    return _plugin_error_free(
      ptr,
    );
  }

  late final _plugin_error_freePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<plugin_error_t>)>>(
      'plugin_error_free');
  late final _plugin_error_free = _plugin_error_freePtr
      .asFunction<void Function(ffi.Pointer<plugin_error_t>)>();

  void plugin_option_error_free(
    ffi.Pointer<plugin_option_error_t> ptr,
  ) {
    return _plugin_option_error_free(
      ptr,
    );
  }

  late final _plugin_option_error_freePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<plugin_option_error_t>)>>('plugin_option_error_free');
  late final _plugin_option_error_free = _plugin_option_error_freePtr
      .asFunction<void Function(ffi.Pointer<plugin_option_error_t>)>();

  void plugin_string_set(
    ffi.Pointer<plugin_string_t> ret,
    ffi.Pointer<ffi.Char> s,
  ) {
    return _plugin_string_set(
      ret,
      s,
    );
  }

  late final _plugin_string_setPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<plugin_string_t>,
              ffi.Pointer<ffi.Char>)>>('plugin_string_set');
  late final _plugin_string_set = _plugin_string_setPtr.asFunction<
      void Function(ffi.Pointer<plugin_string_t>, ffi.Pointer<ffi.Char>)>();

  void plugin_string_dup(
    ffi.Pointer<plugin_string_t> ret,
    ffi.Pointer<ffi.Char> s,
  ) {
    return _plugin_string_dup(
      ret,
      s,
    );
  }

  late final _plugin_string_dupPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<plugin_string_t>,
              ffi.Pointer<ffi.Char>)>>('plugin_string_dup');
  late final _plugin_string_dup = _plugin_string_dupPtr.asFunction<
      void Function(ffi.Pointer<plugin_string_t>, ffi.Pointer<ffi.Char>)>();

  void plugin_string_free(
    ffi.Pointer<plugin_string_t> ret,
  ) {
    return _plugin_string_free(
      ret,
    );
  }

  late final _plugin_string_freePtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<plugin_string_t>)>>(
      'plugin_string_free');
  late final _plugin_string_free = _plugin_string_freePtr
      .asFunction<void Function(ffi.Pointer<plugin_string_t>)>();
}

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

final class max_align_t extends ffi.Opaque {}

final class plugin_string_t extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Size()
  external int len;
}

final class flutter_renderer_alignment_own_alignment_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_alignment_borrow_alignment_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_alignment_own_alignment_directional_t
    extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_alignment_borrow_alignment_directional_t
    extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_alignment_alignment_geometry_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;

  external UnnamedUnion1 val;
}

final class UnnamedUnion1 extends ffi.Union {
  external flutter_renderer_alignment_own_alignment_t alignment;

  external flutter_renderer_alignment_own_alignment_directional_t
      alignment_directional;
}

final class flutter_renderer_enums_main_axis_alignment_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;
}

final class flutter_renderer_enums_text_direction_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;
}

final class flutter_renderer_enums_vertical_direction_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;
}

final class flutter_renderer_enums_main_axis_size_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;
}

final class flutter_renderer_enums_text_baseline_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;
}

final class flutter_renderer_enums_cross_axis_alignment_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;
}

final class flutter_renderer_widget_own_row_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_borrow_row_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_own_col_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_borrow_col_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_own_text_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_borrow_text_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_own_text_rich_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_borrow_text_rich_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_widget_widget_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;

  external UnnamedUnion2 val;
}

final class UnnamedUnion2 extends ffi.Union {
  external flutter_renderer_widget_own_col_t col;

  external flutter_renderer_widget_own_row_t row;

  external flutter_renderer_widget_own_text_t text;

  external flutter_renderer_widget_own_text_rich_t text_rich;
}

final class flutter_renderer_widget_list_widget_t extends ffi.Struct {
  external ffi.Pointer<flutter_renderer_widget_widget_t> ptr;

  @ffi.Size()
  external int len;
}

final class flutter_renderer_widget_option_cross_axis_alignment_t
    extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external flutter_renderer_widget_cross_axis_alignment_t val;
}

typedef flutter_renderer_widget_cross_axis_alignment_t
    = flutter_renderer_enums_cross_axis_alignment_t;

final class flutter_renderer_widget_option_main_axis_alignment_t
    extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external flutter_renderer_widget_main_axis_alignment_t val;
}

typedef flutter_renderer_widget_main_axis_alignment_t
    = flutter_renderer_enums_main_axis_alignment_t;

final class flutter_renderer_widget_option_main_axis_size_t extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external flutter_renderer_widget_main_axis_size_t val;
}

typedef flutter_renderer_widget_main_axis_size_t
    = flutter_renderer_enums_main_axis_size_t;

final class flutter_renderer_widget_option_text_direction_t extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external flutter_renderer_widget_text_direction_t val;
}

typedef flutter_renderer_widget_text_direction_t
    = flutter_renderer_enums_text_direction_t;

final class flutter_renderer_widget_option_text_baseline_t extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external flutter_renderer_widget_text_baseline_t val;
}

typedef flutter_renderer_widget_text_baseline_t
    = flutter_renderer_enums_text_baseline_t;

final class flutter_renderer_widget_option_vertical_direction_t
    extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external flutter_renderer_widget_vertical_direction_t val;
}

typedef flutter_renderer_widget_vertical_direction_t
    = flutter_renderer_enums_vertical_direction_t;

final class flutter_renderer_renderer_error_t extends ffi.Struct {
  @ffi.Uint8()
  external int tag;
}

final class flutter_renderer_renderer_own_renderer_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_renderer_borrow_renderer_t extends ffi.Struct {
  @ffi.Int32()
  external int __handle;
}

final class flutter_renderer_renderer_option_error_t extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external flutter_renderer_renderer_error_t val;
}

final class plugin_option_error_t extends ffi.Struct {
  @ffi.Bool()
  external bool is_some;

  external plugin_error_t val;
}

typedef plugin_error_t = flutter_renderer_renderer_error_t;
typedef flutter_renderer_renderer_widget_t = flutter_renderer_widget_widget_t;
typedef plugin_own_renderer_t = flutter_renderer_renderer_own_renderer_t;
typedef flutter_renderer_widget_alignment_geometry_t
    = flutter_renderer_alignment_alignment_geometry_t;

const int _STDINT_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2X = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C2X_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 39;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_INTN_H = 1;

const int _BITS_STDINT_UINTN_H = 1;

const int _BITS_STDINT_LEAST_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;

const int true1 = 1;

const int false1 = 0;

const int FLUTTER_RENDERER_ALIGNMENT_ALIGNMENT_GEOMETRY_ALIGNMENT = 0;

const int FLUTTER_RENDERER_ALIGNMENT_ALIGNMENT_GEOMETRY_ALIGNMENT_DIRECTIONAL =
    1;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_START = 0;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_END = 1;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_CENTER = 2;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_SPACE_BETWEEN = 3;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_SPACE_AROUND = 4;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_ALIGNMENT_SPACE_EVENLY = 5;

const int FLUTTER_RENDERER_ENUMS_TEXT_DIRECTION_RTL = 0;

const int FLUTTER_RENDERER_ENUMS_TEXT_DIRECTION_LTR = 1;

const int FLUTTER_RENDERER_ENUMS_VERTICAL_DIRECTION_UP = 0;

const int FLUTTER_RENDERER_ENUMS_VERTICAL_DIRECTION_DOWN = 1;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_SIZE_MIN = 0;

const int FLUTTER_RENDERER_ENUMS_MAIN_AXIS_SIZE_MAX = 1;

const int FLUTTER_RENDERER_ENUMS_TEXT_BASELINE_ALPHABETIC = 0;

const int FLUTTER_RENDERER_ENUMS_TEXT_BASELINE_IDEOGRAPHIC = 1;

const int FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_START = 0;

const int FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_END = 1;

const int FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_CENTER = 2;

const int FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_STRETCH = 3;

const int FLUTTER_RENDERER_ENUMS_CROSS_AXIS_ALIGNMENT_BASELINE = 4;

const int FLUTTER_RENDERER_WIDGET_WIDGET_COL = 0;

const int FLUTTER_RENDERER_WIDGET_WIDGET_ROW = 1;

const int FLUTTER_RENDERER_WIDGET_WIDGET_TEXT = 2;

const int FLUTTER_RENDERER_WIDGET_WIDGET_TEXT_RICH = 3;

const int FLUTTER_RENDERER_RENDERER_ERROR_COMMON = 0;
